### ISSUE TITLE
Error following inference_pipeline.ipynb.

### ISSUE THREAD

**Issue by 10maurycy10** [borisdayma/dalle-mini#214]
During the "generate images" step, I get the following error: 

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "<stdin>", line 5, in p_generate
  File "/home/mz/.local/lib/python3.10/site-packages/dalle_mini/model/modeling.py", line 1649, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(
  File "/home/mz/.local/lib/python3.10/site-packages/transformers/generation_flax_utils.py", line 148, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"] = self.encode(input_ids, params=params, return_dict=True, **encoder_kwargs)
  File "/home/mz/.local/lib/python3.10/site-packages/transformers/models/bart/modeling_flax_bart.py", line 1049, in encode
    return self.module.apply(
  File "/home/mz/.local/lib/python3.10/site-packages/transformers/models/bart/modeling_flax_bart.py", line 1047, in _encoder_forward
    return encode_module(input_ids, attention_mask, position_ids, **kwargs)
  File "/home/mz/.local/lib/python3.10/site-packages/dalle_mini/model/modeling.py", line 1141, in __call__
    hidden_states = self.embed_tokens(input_ids) * self.embed_scale
  File "/home/mz/.local/lib/python3.10/site-packages/flax/linen/linear.py", line 615, in setup
    self.embedding = self.param('embedding',
flax.errors.ScopeParamShapeError: Inconsistent shapes between value and initializer for parameter "embedding" in "/model/encoder/embed_tokens": (1, 50272, 2048), (50272, 2048). (https://flax.readthedocs.io/en/latest/flax.errors.html#flax.errors.ScopeParamShapeError)
```

**Comment by borisdayma** [comment]
Does that happen on the colab as well?

**Comment by zswitten** [comment]
Hi @borisdayma, I am seeing this on the colab, yes.
