### ISSUE TITLE
ImportError when trying to follow the inference pipeline guide

### ISSUE THREAD

**Issue by luni3359** [borisdayma/dalle-mini#258]
I'm trying to follow the [inference pipeline guide](https://github.com/borisdayma/dalle-mini/blob/a72705f46ce29a45d1c56c40b39e12476bfa6584/tools/inference/inference_pipeline.ipynb) and it seems like things were working well until I had to import jax. 

I installed dalle-mini with Poetry in the following way:
```toml
dalle-mini = {git = "https://github.com/borisdayma/dalle-mini", rev="a72705f"}
```

which ended up installing these jax dependencies 
 ```
jax==0.3.13; python_version >= "3.7"
jaxlib==0.3.10; python_version >= "3.7"
```
And this is the error that I'm getting:
<details>
  <summary>Traceback</summary>
  
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config
  File "/home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/jax/_src/lib/__init__.py", line 49, in <module>
    import scipy.signal as _signal
  File "/home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/scipy/signal/__init__.py", line 302, in <module>
    from .filter_design import *
  File "/home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/scipy/signal/filter_design.py", line 16, in <module>
    from scipy import special, optimize, fft as sp_fft
  File "/home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/scipy/optimize/__init__.py", line 421, in <module>
    from ._shgo import shgo
  File "/home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/scipy/optimize/_shgo.py", line 9, in <module>
    from scipy import spatial
  File "/home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/scipy/spatial/__init__.py", line 107, in <module>
    from . import distance, transform
  File "/home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/scipy/spatial/transform/__init__.py", line 19, in <module>
    from .rotation import Rotation, Slerp
ImportError: /home/luni3359/.local/share/pyenv/versions/koa-bot/lib/python3.10/site-packages/scipy/spatial/transform/rotation.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```
</details>

Since it said something about scipy I made sure to install it on my system (just in case, even though Poetry already installed it in the venv) and I'm still stuck. Typing `import jax` alone is sufficient to raise the error but since Poetry resolved the dependencies I thought maybe something was off. I'd appreciate any guidance to solve this, thank you.

**Comment by Ahmedniz1** [comment]
are you running it on windows ? if yes, installing jax will call installation for jaxlib and i guess jaxlib isn't available for windows, you'll have to dockerize it and run it in a containerized environment.

**Comment by luni3359** [comment]
I'm running it on Linux, through pyenv's python 3.10 in a venv.
